"""Callback1 commit

Revision ID: 09fa916de8f7
Revises: 7f036c61ab01
Create Date: 2025-03-06 19:53:49.386148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '09fa916de8f7'
down_revision: Union[str, None] = '7f036c61ab01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the is_missed column as NULLable
    # op.add_column('callbacks', sa.Column('is_missed', sa.Boolean(), nullable=True))
    #
    # # Step 2: Update existing rows with a default value (False)
    # op.execute("UPDATE callbacks SET is_missed = 0 WHERE is_missed IS NULL")
    #
    # # Step 3: Add confirmation_file and confirmation_note columns
    # op.add_column('callbacks', sa.Column('confirmation_file', sa.String(), nullable=True))
    # op.add_column('callbacks', sa.Column('confirmation_note', sa.String(), nullable=True))

    # Note: SQLite doesn't support ALTER COLUMN to set NOT NULL directly.
    # Instead, we rely on the UPDATE to ensure no NULLs, but for strict NOT NULL,
    # we should recreate the table. However, for simplicity, we'll skip recreating
    # the table here and assume the UPDATE handles it. If strict NOT NULL is required,
    # use the table recreation approach below (commented out).

    # # Alternative: Recreate table to enforce NOT NULL (safer but more complex)
    with op.batch_alter_table('callbacks', recreate='always') as batch_op:
        batch_op.drop_column('is_missed')
        batch_op.add_column(sa.Column('is_missed', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('confirmation_file', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_note', sa.String(), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('callbacks', 'confirmation_note')
    op.drop_column('callbacks', 'confirmation_file')
    op.drop_column('callbacks', 'is_missed')
    # ### end Alembic commands ###