"""Add installment settings to ResidentialComplex

Revision ID: 3c172cad203c
Revises: 9e0be0ff02b2
Create Date: 2025-12-08 12:04:35.612142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c172cad203c'
down_revision: Union[str, None] = '9e0be0ff02b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complexes', sa.Column('installment_months', sa.Integer(), nullable=False, server_default='36'))
    op.add_column('residential_complexes', sa.Column('installment_start_date', sa.Date(), nullable=False, server_default='2025-12-01'))
    op.add_column('residential_complexes', sa.Column('hybrid_installment_enabled', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residential_complexes', 'hybrid_installment_enabled')
    op.drop_column('residential_complexes', 'installment_start_date')
    op.drop_column('residential_complexes', 'installment_months')
    # ### end Alembic commands ###
