
"""User commit

Revision ID: 6145bd71b260
Revises: ae9a3ca8f6a9
Create Date: 2025-02-28 17:48:34.404169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6145bd71b260'
down_revision: Union[str, None] = 'ae9a3ca8f6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('installment_payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    op.drop_column('payments', 'updated_at')
    op.drop_column('installment_payments', 'updated_at')
    op.drop_column('expenses', 'updated_at')
    # ### end Alembic commands ###
