"""sql commit

Revision ID: 6c4bfade3f28
Revises: b9af44e58da3
Create Date: 2025-05-05 17:36:59.572555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4bfade3f28'
down_revision: Union[str, None] = 'b9af44e58da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads_prototype', sa.Column('complex_name', sa.String(), nullable=True))
    op.add_column('leads_prototype', sa.Column('number_apartments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads_prototype', 'number_apartments')
    op.drop_column('leads_prototype', 'complex_name')
    # ### end Alembic commands ###
