"""sql1 commit

Revision ID: 76b07c9236fe
Revises: 6c4bfade3f28
Create Date: 2025-05-05 19:52:55.343282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b07c9236fe'
down_revision: Union[str, None] = '6c4bfade3f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads_prototype', sa.Column('block', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads_prototype', 'block')
    # ### end Alembic commands ###
