"""sql3 commit

Revision ID: 792891f5d144
Revises: fc62a1be09b9
Create Date: 2025-05-06 00:38:52.728855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792891f5d144'
down_revision: Union[str, None] = 'fc62a1be09b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads_prototype', sa.Column('down_payment_percent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads_prototype', 'down_payment_percent')
    # ### end Alembic commands ###
