"""add complex data tables

Revision ID: 7eefce3ffaeb
Revises: 8315d22d9eff
Create Date: 2025-10-04 16:34:35.178942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eefce3ffaeb'
down_revision: Union[str, None] = '8315d22d9eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residential_complexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('apartment_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_id', 'block_name', 'floor', 'unit_number', name='uq_apartment_unit')
    )
    op.create_index(op.f('ix_apartment_units_complex_id'), 'apartment_units', ['complex_id'], unique=False)
    op.create_table('chessboard_price_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(), nullable=False),
    sa.Column('price_per_sqm', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_id', 'floor', 'category_key', name='uq_chessboard_price_entry')
    )
    op.create_index(op.f('ix_chessboard_price_entries_complex_id'), 'chessboard_price_entries', ['complex_id'], unique=False)
    op.create_table('contract_registry_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('apartment_number', sa.String(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('down_payment_percent', sa.Float(), nullable=True),
    sa.Column('down_payment_amount', sa.Float(), nullable=True),
    sa.Column('buyer_full_name', sa.String(), nullable=False),
    sa.Column('buyer_passport_series', sa.String(), nullable=True),
    sa.Column('buyer_pinfl', sa.String(), nullable=True),
    sa.Column('issued_by', sa.String(), nullable=True),
    sa.Column('registration_address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('sales_department', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complex_id'], ['residential_complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_id', 'contract_number', name='uq_contract_registry_contract')
    )
    op.create_index(op.f('ix_contract_registry_entries_apartment_id'), 'contract_registry_entries', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_contract_registry_entries_complex_id'), 'contract_registry_entries', ['complex_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_registry_entries_complex_id'), table_name='contract_registry_entries')
    op.drop_index(op.f('ix_contract_registry_entries_apartment_id'), table_name='contract_registry_entries')
    op.drop_table('contract_registry_entries')
    op.drop_index(op.f('ix_chessboard_price_entries_complex_id'), table_name='chessboard_price_entries')
    op.drop_table('chessboard_price_entries')
    op.drop_index(op.f('ix_apartment_units_complex_id'), table_name='apartment_units')
    op.drop_table('apartment_units')
    op.drop_table('residential_complexes')
    # ### end Alembic commands ###
