"""Добавить таблицу campaigns

Revision ID: 8315d22d9eff
Revises: e8314a50ead1
Create Date: 2025-07-26 13:30:09.259905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8315d22d9eff'
down_revision: Union[str, None] = 'e8314a50ead1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
