"""Initial migration

Revision ID: 8d79c54fcc70
Revises: 
Create Date: 2025-02-12 02:31:06.975438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8d79c54fcc70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('lead_actions')
    op.drop_table('accesses')
    op.drop_table('leads_prototype')
    op.drop_table('attendances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('check_in', sa.TIME(), nullable=True),
    sa.Column('check_out', sa.TIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads_prototype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('region', sa.VARCHAR(), nullable=False),
    sa.Column('contact_source', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=4), nullable=False),
    sa.Column('state', sa.VARCHAR(length=16), nullable=False),
    sa.Column('square_meters', sa.INTEGER(), nullable=True),
    sa.Column('rooms', sa.INTEGER(), nullable=True),
    sa.Column('floor', sa.INTEGER(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('payment_type', sa.VARCHAR(), nullable=False),
    sa.Column('monthly_payment', sa.FLOAT(), nullable=True),
    sa.Column('installment_period', sa.INTEGER(), nullable=True),
    sa.Column('installment_markup', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('next_contact_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accesses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource', sa.VARCHAR(), nullable=False),
    sa.Column('permission', sa.VARCHAR(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_actions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_prototype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('login', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=False),
    sa.Column('work_start_time', sa.TIME(), nullable=True),
    sa.Column('work_end_time', sa.TIME(), nullable=True),
    sa.Column('work_days', sqlite.JSON(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('reg_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###
