"""sql9 commit

Revision ID: 99a9e2352109
Revises: 263ce0222449
Create Date: 2025-06-10 20:20:23.426408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a9e2352109'
down_revision: Union[str, None] = '263ce0222449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draw_users', sa.Column('lang', sa.Enum('ru', 'uz', name='userlang'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draw_users', 'lang')
    # ### end Alembic commands ###
