"""Add Telegram Mini App models

Revision ID: ae25742f11fe
Revises: 3c172cad203c
Create Date: 2026-01-11 02:14:11.919019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae25742f11fe'
down_revision: Union[str, None] = '3c172cad203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_miniapp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source_payload', sa.String(length=100), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_prototype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_miniapp_users_telegram_id'), 'telegram_miniapp_users', ['telegram_id'], unique=True)
    op.create_table('apartment_interest_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complex_name', sa.String(), nullable=False),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('time_score', sa.Integer(), nullable=False),
    sa.Column('favorites_bonus', sa.Integer(), nullable=False),
    sa.Column('payment_view_bonus', sa.Integer(), nullable=False),
    sa.Column('map_view_bonus', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_miniapp_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'complex_name', 'block_name', 'floor', 'unit_number', name='uq_interest_user_apartment')
    )
    op.create_index(op.f('ix_apartment_interest_scores_complex_name'), 'apartment_interest_scores', ['complex_name'], unique=False)
    op.create_index(op.f('ix_apartment_interest_scores_user_id'), 'apartment_interest_scores', ['user_id'], unique=False)
    op.create_table('miniapp_lead_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('LEAVE_REQUEST', 'BOOK', 'QUESTION', name='miniappleadrequesttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'CONVERTED', name='miniappleadrequeststatus'), nullable=False),
    sa.Column('complex_name', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('unit_number', sa.String(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('price_snapshot', sa.Float(), nullable=True),
    sa.Column('payment_type_interest', sa.String(), nullable=True),
    sa.Column('interest_score', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_prototype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_miniapp_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miniapp_lead_requests_user_id'), 'miniapp_lead_requests', ['user_id'], unique=False)
    op.drop_table('lost_and_found')
    op.create_index(op.f('ix_chessboard_price_entries_complex_id'), 'chessboard_price_entries', ['complex_id'], unique=False)
    op.add_column('leads_prototype', sa.Column('telegram_user_id', sa.BigInteger(), nullable=True))
    op.add_column('leads_prototype', sa.Column('interest_score_snapshot', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leads_prototype_telegram_user_id'), 'leads_prototype', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_prototype_telegram_user_id'), table_name='leads_prototype')
    op.drop_column('leads_prototype', 'interest_score_snapshot')
    op.drop_column('leads_prototype', 'telegram_user_id')
    op.drop_index(op.f('ix_chessboard_price_entries_complex_id'), table_name='chessboard_price_entries')
    op.create_table('lost_and_found',
    sa.Column('rootpgno', sa.INTEGER(), nullable=True),
    sa.Column('pgno', sa.INTEGER(), nullable=True),
    sa.Column('nfield', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.Column('c4', sa.NullType(), nullable=True),
    sa.Column('c5', sa.NullType(), nullable=True),
    sa.Column('c6', sa.NullType(), nullable=True),
    sa.Column('c7', sa.NullType(), nullable=True),
    sa.Column('c8', sa.NullType(), nullable=True),
    sa.Column('c9', sa.NullType(), nullable=True),
    sa.Column('c10', sa.NullType(), nullable=True),
    sa.Column('c11', sa.NullType(), nullable=True),
    sa.Column('c12', sa.NullType(), nullable=True),
    sa.Column('c13', sa.NullType(), nullable=True),
    sa.Column('c14', sa.NullType(), nullable=True),
    sa.Column('c15', sa.NullType(), nullable=True),
    sa.Column('c16', sa.NullType(), nullable=True),
    sa.Column('c17', sa.NullType(), nullable=True),
    sa.Column('c18', sa.NullType(), nullable=True),
    sa.Column('c19', sa.NullType(), nullable=True),
    sa.Column('c20', sa.NullType(), nullable=True),
    sa.Column('c21', sa.NullType(), nullable=True),
    sa.Column('c22', sa.NullType(), nullable=True),
    sa.Column('c23', sa.NullType(), nullable=True)
    )
    op.drop_index(op.f('ix_miniapp_lead_requests_user_id'), table_name='miniapp_lead_requests')
    op.drop_table('miniapp_lead_requests')
    op.drop_index(op.f('ix_apartment_interest_scores_user_id'), table_name='apartment_interest_scores')
    op.drop_index(op.f('ix_apartment_interest_scores_complex_name'), table_name='apartment_interest_scores')
    op.drop_table('apartment_interest_scores')
    op.drop_index(op.f('ix_telegram_miniapp_users_telegram_id'), table_name='telegram_miniapp_users')
    op.drop_table('telegram_miniapp_users')
    # ### end Alembic commands ###
