"""User commit

Revision ID: ae9a3ca8f6a9
Revises: c3e0142bf9ac
Create Date: 2025-02-24 20:05:42.779729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9a3ca8f6a9'
down_revision: Union[str, None] = 'c3e0142bf9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
