"""sql10 commit

Revision ID: e8314a50ead1
Revises: 64a20f0d6d95
Create Date: 2025-06-10 21:32:57.831286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8314a50ead1'
down_revision: Union[str, None] = '64a20f0d6d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'uz', name='userlang'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_users_phone'), 'draw_users', ['phone'], unique=True)
    op.create_index(op.f('ix_draw_users_telegram_id'), 'draw_users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draw_users_telegram_id'), table_name='draw_users')
    op.drop_index(op.f('ix_draw_users_phone'), table_name='draw_users')
    op.drop_table('draw_users')
    # ### end Alembic commands ###
