"""Expense commit

Revision ID: f2c3a2de5189
Revises: 09fa916de8f7
Create Date: 2025-03-07 20:16:47.475163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c3a2de5189'
down_revision: Union[str, None] = '09fa916de8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.Enum('HOUSEHOLD', 'SALARY', 'OTHER', name='expensecategory'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###
