"""sql2 commit

Revision ID: fc62a1be09b9
Revises: 76b07c9236fe
Create Date: 2025-05-05 23:36:17.730945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc62a1be09b9'
down_revision: Union[str, None] = '76b07c9236fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads_prototype', sa.Column('square_meters_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads_prototype', 'square_meters_price')
    # ### end Alembic commands ###
